/*第五章习题5-11编写产生冰雹的程序*/
#include <stdio.h>
#define maxn 1005
int n, num, tmp;
int a[maxn];
void hailstone(int x)
{
	printf("%4d", x);
	if (++tmp == 6) putchar('\n'), tmp = 0;
	if (x == 1)
	{
		num++;
		return;
	}
	if (x % 2 == 0)
	{
		hailstone(x / 2);
		num++;
	}
	else
	{
		hailstone(3 * x + 1);
		num++;
	}
}
int main09()
{
	scanf_s("%d", &n);
	printf("Hailstone generated by %d:\n", n);
	hailstone(n);
	if (num % 6 != 0) putchar('\n');
	printf("Number of hailstone generated:%d", num);
	return 0;
}